''
'' Colors taken from the css file of the BS theme
''
!$PRIMARY = %hsl_color(%random(1,359), %random(101), %random(101))
!$SECONDARY = %hsl_color(%random(1,359), %random(101), %random(101))
!$LIGHT = %hsl_color(%random(1,359), %random(101), %random(101))
!$DARK = %hsl_color(%random(1,359), %random(101), %random(101))

!$SUCCESS = %hsl_color(%random(1,359), %random(101), %random(101))
!$INFO = %hsl_color(%random(1,359), %random(101), %random(101))
!$WARNING = %hsl_color(%random(1,359), %random(101), %random(101))
!$DANGER = %hsl_color(%random(1,359), %random(101), %random(101))

!$LIGHTEN_DARKEN_FACTOR = 20
!$TRANSPARENCY_LEVEL = 90

'' *_LIGHT = tint (lighter) of the main color of 80%
''          where TINT is calculated by clr + (255-clr) * tint_factor
'' *_DARK = shade (darker) of the main color of 80%
''          and SHADE is calculated by clr * (1 - shade_factor)
''
!$BACKGROUND = %hsl_color(%random(1,359), %random(101), %random(101))
!$FOREGROUND = %hsl_color(%random(1,359), %random(101), %random(101))
!$PRIMARY_LIGHT = %lighten($PRIMARY, $LIGHTEN_DARKEN_FACTOR)
!$PRIMARY_DARK = %darken($PRIMARY, $LIGHTEN_DARKEN_FACTOR)
!$PRIMARY_TEXT = $PRIMARY
!$SECONDARY_LIGHT = %lighten($SECONDARY, $LIGHTEN_DARKEN_FACTOR)
!$SECONDARY_DARK = %darken($SECONDARY, $LIGHTEN_DARKEN_FACTOR)
!$SECONDARY_TEXT = $SECONDARY_DARK
!$INFO_LIGHT = %lighten($INFO, $LIGHTEN_DARKEN_FACTOR)
!$INFO_TEXT = $INFO
!$SUCCESS_LIGHT = %lighten($SUCCESS, $LIGHTEN_DARKEN_FACTOR)
!$SUCCESS_TEXT = $SUCCESS
!$WARNING_LIGHT = %lighten($WARNING, $LIGHTEN_DARKEN_FACTOR)
!$WARNING_TEXT = $WARNING
!$DANGER_LIGHT = %lighten($DANGER, $LIGHTEN_DARKEN_FACTOR)
!$DANGER_TEXT = $DANGER
!$ARROW = $PRIMARY_DARK
!$BOX_BACKGROUND = $FOREGROUND
!$PARTICIPANT_BACKGROUND = $SECONDARY


' skinparam backgroundColor $BACKGROUND
skinparam useBetaStyle false