@startuml

!$COMPONENTS_PUML = "https://raw.githubusercontent.com/segFallt/plantUML-components/v2.1.0/dist"
!include $COMPONENTS_PUML/3rdParty/aws14/AwsCommon.iuml

' skinparam linetype polyline
 skinparam linetype ortho

EC2(Smadex, "Smadex Service", " ")
Users(Users, "Users", " ")
Traditionalserver(AdExchange, "Ad Exchange", " ")
Mobileclient(Mobile, "Publisher app or web", " ")

Users -down-> Mobile: 1. Visits
Mobile -right-> AdExchange: 2. Start auction
AdExchange -right-> Smadex: 3. Bid request / response
Smadex -left-> Mobile: 4. Show Ad
Users -right-> Smadex: 5. Impression / click / install / event {request id}
@enduml
