

!procedure $success($msg)
  <font color=$SUCCESS><b>$msg
!endprocedure

!procedure $failure($msg)
  <font color=$DANGER><b>$msg
!endprocedure

!procedure $warning($msg)
  <font color=$WARNING><b>$msg
!endprocedure

!procedure $primary_scheme()
	FontColor $PRIMARY_TEXT
	BorderColor $PRIMARY
	BackgroundColor $SECONDARY
	' BackgroundColor $BGCOLOR
!endprocedure


''
'' Style settings
''


<style>
  root {
    BackgroundColor $BGCOLOR
    FontColor $PRIMARY_TEXT
    HyperLinkColor $ORANGE
    LineColor $PRIMARY_DARK
    LineThickness 1
    Margin 10
    Padding 6
    Shadowing 0.0
  }
  node {
   Padding 15
   roundcorner 20
   BackgroundColor $BGCOLOR
  }
  caption {
    LineThickness 0
  }
  footer {
    LineThickness 0
  }
  group {
	LineThickness 2
  }
  groupHeader {
    BackgroundColor $SECONDARY
    FontColor $INFO
    ' FontStyle bold
  }
  header {
    LineThickness 0
  }
  lifeline {
	LineThickness 2
  }
  referenceHeader {
    BackgroundColor $BGCOLOR
    FontColor $DARK
    FontStyle bold
  }
  separator {
    BackgroundColor $SECONDARY
    ' BackgroundColor $FGCOLOR
    FontColor $PRIMARY_TEXT
    ' FontColor $BGCOLOR
    FontStyle bold
  }
  title {
	' $primary_scheme()
	FontSize 20
	BorderRoundCorner            8
	BorderThickness 	         1
	BackgroundColor  $BGCOLOR
	FontColor $PRIMARY_TEXT
	' FontColor $PRIMARY
	BorderColor $PRIMARY
	' BorderColor $SECONDARY
  }
  nwdiagDiagram {
	network {
		$primary_scheme()
		LineColor $PRIMARY
		LineThickness 1.0
		FontColor $PRIMARY_DARK
	}
	server {
		$primary_scheme()
	}
	arrow {
		FontColor $PRIMARY_DARK
		LineColor $ARROW
		LineColor $PRIMARY_DARK
	}
	group {
		BackGroundColor $LIGHT
		LineColor $LIGHT_DARK
		LineThickness 2.0
		Margin 5
		Padding 5
	}
  }
  ganttDiagram {
	task {
		$primary_scheme()
		LineColor $PRIMARY
		Margin 10
		Padding 6
	}
	note {
		FontColor $INFO_TEXT
		LineColor $INFO_DARK
		BackGroundColor $BGCOLOR
	}
	separator {
		LineColor $SECONDARY_DARK
		BackgroundColor $SECONDARY
		' BackGroundColor $BGCOLOR
		FontColor $SECONDARY_TEXT
	}
	milestone {
		FontColor $INFO
		FontSize 16
		FontStyle italic
		BackGroundColor $SECONDARY
		LineColor $SECONDARY_DARK
	}
	timeline {
		BackgroundColor $SECONDARY
		' FontColor $SECONDARY_TEXT
		FontColor $INFO
		FontName "Verdana"
	}
	closed {
		BackgroundColor $WARNING_DARK
		FontColor $WARNING_TEXT
	}
  }
</style>
''
'' Global Default Values
''
skinparam defaultFontName       "Verdana"
skinparam defaultFontSize       12
skinparam dpi                   100
skinparam shadowing             false
skinparam roundcorner           8
skinparam ParticipantPadding    40
skinparam BoxPadding            40
skinparam Padding               5
skinparam ArrowColor            $GRAY
skinparam stereotype {
    CBackgroundColor $SECONDARY_LIGHT
    CBorderColor $SECONDARY_DARK
    ABackgroundColor $SUCCESS_LIGHT
    ABorderColor $SUCCESS_DARK
    IBackgroundColor $DANGER_LIGHT
    IBorderColor $DANGER_DARK
    EBackgroundColor $WARNING_LIGHT
    EBorderColor $WARNING_DARK
    NBackgroundColor $INFO_LIGHT
    NBorderColor $INFO_DARK
}
skinparam title {
	FontColor	                 $PRIMARY_TEXT
	' FontColor	                 $PRIMARY
	BorderColor	                 $PRIMARY_DARK
	' BorderColor	                 $SECONDARY_DARK
	FontSize	    	         15
	BorderRoundCorner            8
	BorderThickness 	         1
	BackgroundColor              $BGCOLOR
}

skinparam legend {
	BackgroundColor $BGCOLOR
	BorderColor $SECONDARY_DARK
	FontColor $DARK
}

!startsub swimlane
skinparam swimlane {
	BorderColor $INFO
	BorderThickness 2
	TitleBackgroundColor  $SECONDARY_LIGHT-$SECONDARY
	TitleFontColor $PRIMARY_TEXT
	' TitleFontColor $PRIMARY
}
!endsub

!startsub activity

skinparam activity {
	$primary_scheme()
	BarColor $SUCCESS
	StartColor $INFO
	EndColor $INFO
	''
	DiamondBackgroundColor $SECONDARY
	' DiamondBackgroundColor $BGCOLOR
  	DiamondBorderColor $PRIMARY
  	' DiamondBorderColor $SECONDARY_DARK
	DiamondFontColor $PRIMARY_TEXT
	' DiamondFontColor $SECONDARY_TEXT
}
!endsub

!startsub participant

skinparam participant {
	$primary_scheme()
	BorderThickness 2
}
!endsub

!startsub actor

skinparam actor {
	$primary_scheme()
}
!endsub

!startsub arrow

skinparam arrow {
	Thickness 1
	' Thickness 3
	Color $ARROW
	' Color $PRIMARY
	FontColor $FGCOLOR
}
!endsub

!startsub sequence

skinparam sequence {
	BorderColor $PRIMARY
	' For some reason sequence title font color does not pick up from global
	TitleFontColor $PRIMARY_TEXT
	' TitleFontColor $PRIMARY
	TitleBorderColor $PRIMARY
	BackgroundColor $BGCOLOR
	StartColor $PRIMARY
	EndColor $PRIMARY
	''
	BoxBackgroundColor $BOXBACKGROUND
	BoxBorderColor $GRAY
	BoxFontColor $DARK
	''
	DelayFontColor $DARK
	''

	LifeLineBorderColor $PRIMARY
	' LifeLineBorderColor $SECONDARY_DARK
	SequenceLifeLineBorderThickness 4
	' LifeLineBorderThickness 2
	LifeLineBackgroundColor $SECONDARY
	' LifeLineBackgroundColor $BGCOLOR
	''
	GroupBorderColor $GRAY
	GroupFontColor $DARK
	GroupHeaderFontColor $INFO_TEXT
	''
	DividerBackgroundColor $SECONDARY
	' DividerBackgroundColor $BGCOLOR
    DividerBorderColor $GRAY
    DividerBorderThickness 2
    DividerFontColor $DARK
	''
	ReferenceBackgroundColor $BGCOLOR
	ReferenceBorderColor $GRAY
	ReferenceFontColor $DARK
	ReferenceHeaderFontColor $INFO_TEXT
	''
	StereotypeFontColor $PRIMARY_TEXT
}
!endsub

skinparam SequenceLifeLineBorderThickness 2

!startsub partition

skinparam partition {
	BorderColor $PRIMARY
	FontColor $PRIMARY
	BackgroundColor $BGCOLOR
}
!endsub

!startsub collections

skinparam collections {
	$primary_scheme()
}
!endsub

!startsub control

skinparam control {
	$primary_scheme()
}
!endsub

!startsub entity

skinparam entity {
	$primary_scheme()
}
!endsub

!startsub boundary

skinparam boundary {
	$primary_scheme()
}
!endsub

!startsub agent

skinparam agent {
	BackgroundColor $BGCOLOR
	BorderColor #999999
	FontColor #333333
}
!endsub

!startsub note

skinparam note {
	BorderThickness 1
	BackgroundColor $SECONDARY
	' BackgroundColor $BGCOLOR
	BorderColor $PRIMARY
	' BorderColor $INFO
	FontColor $PRIMARY_TEXT
	' FontColor $INFO_TEXT
}
!endsub

!startsub artifact

skinparam artifact {
	BackgroundColor $BGCOLOR
	BorderColor $GRAY
	FontColor $GRAY
}
!endsub

!startsub component

skinparam component {
	$primary_scheme()
	' BackgroundColor $BGCOLOR
	' BorderColor  $SUCCESS
	' FontColor $SUCCESS_TEXT
}
!endsub

!startsub interface

skinparam interface {
	BackgroundColor $SECONDARY
	' BackgroundColor $BGCOLOR
	BorderColor  $DANGER
	FontColor $DARK
}
!endsub

!startsub storage

skinparam storage {
	BackgroundColor $BGCOLOR
  	BorderColor $WARNING
	FontColor $WARNING_TEXT
}
!endsub

!startsub node

skinparam node {
	BackgroundColor $BGCOLOR
	BorderColor $DARK
	FontColor $DARK
}
!endsub

!startsub cloud

skinparam cloud {
	BackgroundColor #F2FCFE-#eeeeee
	BorderColor #F2FCFE
	FontColor $DARK
}
!endsub

!startsub database

skinparam database {
	$primary_scheme()
}
!endsub

!startsub class

skinparam class {
	$primary_scheme()
	FontColor $DARK
	' HeaderBackgroundColor $PRIMARY_LIGHT
	' HeaderBackgroundColor $PRIMARY-$PRIMARY_DARK
	StereotypeFontColor $DARK
	BorderThickness 1
	AttributeFontColor $DARK
	AttributeFontSize 11
}
!endsub

!startsub object

skinparam object {
	$primary_scheme()
	StereotypeFontColor $DARK
	BorderThickness 1
	AttributeFontColor $SECONDARY_DARK
	AttributeFontSize 11
}
!endsub

!startsub usecase

skinparam usecase {
	$primary_scheme()
	BorderThickness 2
	StereotypeFontColor $PRIMARY
}
!endsub

!startsub rectangle

skinparam rectangle {
	$primary_scheme()
	BorderThickness 2
	StereotypeFontColor $PRIMARY
}
!endsub

!startsub package

skinparam package {
	' BackgroundColor transparent
	BackgroundColor $BGCOLOR
  	BorderColor $PRIMARY
	FontColor $DARK
	' FontColor $PRIMARY
	BorderThickness 2
}
!endsub

!startsub folder

skinparam folder {
	BackgroundColor $BGCOLOR
  	BorderColor $WARNING
	FontColor $WARNING
	BorderThickness 2
}
!endsub

!startsub frame

skinparam frame {
	BackgroundColor $BGCOLOR
  	BorderColor $INFO
	FontColor $INFO_TEXT
	BorderThickness 2
}
!endsub

!startsub state

skinparam state {
	$primary_scheme()
	StartColor $INFO
	EndColor $INFO
	AttributeFontColor $PRIMARY_TEXT
	AttributeFontSize 11
}
!endsub

!startsub queue

skinparam queue {
	$primary_scheme()
}
!endsub

!startsub card

skinparam card {
	BackgroundColor $BGCOLOR
	BorderColor $INFO
	FontColor $INFO_TEXT
}
!endsub

!startsub file

skinparam file {
	BackgroundColor $BGCOLOR
	BorderColor $GRAY
	FontColor $GRAY
}
!endsub

!startsub stack

skinparam stack {
	$primary_scheme()
}
!endsub

!if (%variable_exists("LEGACY"))
!$LEGACY = "true"
!endif

!if (%getenv("LEGACY") == "true")
!$LEGACY = "true"
!endif

!if (%variable_exists("$LEGACY"))

skinparam useBetaStyle true

!startsub mindmap

<style>
style mindmapDiagram {
  'Padding 8
  Margin 8
  LineThickness 2.0
  FontColor $PRIMARY_TEXT
  LineColor $SECONDARY
  BackGroundColor $PRIMARY_LIGHT-$PRIMARY
}
wbsDiagram {
  'Padding 8
  Margin 8
  LineThickness 2.0
  FontColor $PRIMARY_TEXT
  LineColor $PRIMARY
  BackGroundColor $PRIMARY_LIGHT-$PRIMARY
}
</style>
!endsub
!endif